//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy_basketball_web_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1992_1993
    {
        public string Rk { get; set; }
        public string Player { get; set; }
        public string Pos { get; set; }
        public string Age { get; set; }
        public string Tm { get; set; }
        public string G { get; set; }
        public string GS { get; set; }
        public string MP { get; set; }
        public string FG { get; set; }
        public string FGA { get; set; }
        public string FG_ { get; set; }
        public string C3P { get; set; }
        public string C3PA { get; set; }
        public string C3P_ { get; set; }
        public string C2P { get; set; }
        public string C2PA { get; set; }
        public string C2P_ { get; set; }
        public string eFG_ { get; set; }
        public string FT { get; set; }
        public string FTA { get; set; }
        public string FT_ { get; set; }
        public string ORB { get; set; }
        public string DRB { get; set; }
        public string TRB { get; set; }
        public string AST { get; set; }
        public string STL { get; set; }
        public string BLK { get; set; }
        public string TOV { get; set; }
        public string PF { get; set; }
        public string PTSâ__ { get; set; }
    }
}
